package taxi_together.taxi_together.exception.exception

import taxi_together.taxi_together.exception.message.MemberExceptionMessage

class MemberException(val memberExceptionMessage: MemberExceptionMessage) : RuntimeException(memberExceptionMessage.message)